name: Testing

on:
  push:
    branches: [ "main" ]

env:
  BUILD_TYPE: Release

jobs:
  build:
    env:
      CC: gcc-13
      CXX: g++-13
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Configure CMake
        run: |
          vcpkg/bootstrap-vcpkg.sh
          cd src
          cmake -B=build -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}}

      - name: Build
        run: |
          cd tests
          cmake --build build --config ${{env.BUILD_TYPE}}
  testing:
    env:
      CC: gcc-13
      CXX: g++-13
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - uses: actions/checkout@v3
        with:
          repository: microsoft/vcpkg
          path: vcpkg

      - name: Configure CMake
        run: |
          vcpkg/bootstrap-vcpkg.sh
          cd tests
          cmake -DCMAKE_TOOLCHAIN_FILE=${{ github.workspace }}/vcpkg/scripts/buildsystems/vcpkg.cmake -B=build -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}}

      - name: Build
        run: |
          cd tests
          cmake --build build --config ${{env.BUILD_TYPE}}

      - name: Run
        run: |
          cd tests
          ./build/test
